# Generated by Django 3.1.4 on 2020-12-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_km', models.IntegerField()),
                ('over_free_km_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fixedprice', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
