# Generated by Django 3.1.4 on 2020-12-29 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_km', models.IntegerField()),
                ('over_free_km_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fixedprice', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='RentalObjectPriceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=1)),
                ('price_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='price_models.pricemodel')),
            ],
        ),
    ]
