# Generated by Django 3.1.4 on 2020-12-29 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price_models', '0001_initial'),
        ('rental_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalobjectpricemodel',
            name='rental_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_objects.rentalobject'),
        ),
        migrations.AddField(
            model_name='pricemodel',
            name='rental_objects',
            field=models.ManyToManyField(through='price_models.RentalObjectPriceModel', to='rental_objects.RentalObject'),
        ),
    ]
