# Generated by Django 3.1.4 on 2021-01-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price_models', '0001_initial'),
        ('rental_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricemodel',
            name='rental_objects',
            field=models.ManyToManyField(blank=True, to='rental_objects.RentalObject'),
        ),
        migrations.AddField(
            model_name='price',
            name='price_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='price_models.pricemodel'),
        ),
    ]
