# Generated by Django 3.1.4 on 2020-12-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20201224_1602'),
        ('price_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPriceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('price_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_models.pricemodel')),
            ],
        ),
    ]
