# Generated by Django 3.1.4 on 2021-01-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_models', '0002_auto_20210102_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricemodel',
            name='rental_objects',
        ),
    ]
