# Generated by Django 3.1.4 on 2020-12-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_models', '0003_pricemodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=1)),
                ('free_km', models.IntegerField()),
                ('km_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fixedprice', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='rentalobjectpricemodel',
            name='price_model',
        ),
        migrations.RemoveField(
            model_name='rentalobjectpricemodel',
            name='rental_object',
        ),
        migrations.RemoveField(
            model_name='pricemodel',
            name='fixedprice',
        ),
        migrations.RemoveField(
            model_name='pricemodel',
            name='free_km',
        ),
        migrations.RemoveField(
            model_name='pricemodel',
            name='over_free_km_price',
        ),
        migrations.RemoveField(
            model_name='pricemodel',
            name='rental_objects',
        ),
    ]
