# Generated by Django 3.1.4 on 2020-12-30 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_models', '0004_auto_20201230_0024'),
        ('reservations', '0002_remove_reservation_rental_object_price_model'),
        ('rental_objects', '0002_auto_20201230_0024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalObjectPriceModel',
        ),
        migrations.AddField(
            model_name='priceperday',
            name='price_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_models.pricemodel'),
        ),
    ]
