# Generated by Django 3.1.4 on 2020-12-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20201231_1723'),
        ('price_models', '0008_auto_20201230_0426'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyPrice',
            new_name='Price',
        ),
    ]
