# Generated by Django 3.1.4 on 2020-12-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notregistereduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotRegisteredProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address')),
            ],
        ),
        migrations.AlterField(
            model_name='notregistereduser',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.notregisteredprofile'),
        ),
    ]
