# Generated by Django 3.1.4 on 2021-01-01 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210101_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notregistereduser',
            name='profile',
        ),
        migrations.AddField(
            model_name='notregisteredprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.notregistereduser'),
        ),
    ]
