# Generated by Django 3.1.4 on 2020-12-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental_objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental_objects.rentalobject')),
            ],
        ),
    ]
