# Generated by Django 3.1.4 on 2020-12-30 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='rental_object_price_model',
        ),
    ]
