# Generated by Django 3.1.4 on 2020-12-31 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_models', '0008_auto_20201230_0426'),
        ('reservations', '0003_reservation_price_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='price_model',
        ),
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price_models.dailyprice'),
        ),
    ]
