# Generated by Django 3.1.4 on 2020-12-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20201226_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notregistereduser',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
