# Generated by Django 3.1.4 on 2020-12-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20201226_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='not_registered_user',
        ),
        migrations.DeleteModel(
            name='NotRegisteredUser',
        ),
    ]
