# Generated by Django 3.1.4 on 2020-12-27 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notregistereduser'),
        ('reservations', '0006_auto_20201227_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='not_registered_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.notregistereduser'),
        ),
    ]
