# Generated by Django 3.1.4 on 2020-12-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='multiple_choice',
            field=models.BooleanField(default=False),
        ),
    ]
