# Generated by Django 3.1.4 on 2020-12-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('truck', 'truck'), ('car', 'car')], max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('year_of_manufacture', models.DateField()),
            ],
        ),
    ]
