# Generated by Django 3.1.4 on 2020-12-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_models', '0002_carpricemodel'),
        ('cars', '0002_auto_20201224_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_models',
            field=models.ManyToManyField(through='price_models.CarPriceModel', to='price_models.PriceModel'),
        ),
    ]
