# Generated by Django 3.1.4 on 2020-12-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_price_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year_of_manufacture',
            field=models.IntegerField(),
        ),
    ]
