# Generated by Django 3.1.4 on 2020-12-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20201228_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year_of_manufacture',
        ),
    ]
