# Generated by Django 3.1.4 on 2020-12-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_auto_20201224_1602'),
        ('properties', '0002_property_multiple_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.car')),
                ('properties', models.ManyToManyField(to='properties.PropertyValue')),
            ],
        ),
    ]
