# Generated by Django 3.1.4 on 2020-12-29 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price_models', '0001_initial'),
        ('cars', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_manufacture', models.IntegerField()),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.car')),
                ('price_models', models.ManyToManyField(through='price_models.RentalObjectPriceModel', to='price_models.PriceModel')),
                ('properties', models.ManyToManyField(blank=True, to='properties.PropertyValue')),
            ],
        ),
    ]
