# Generated by Django 3.1.4 on 2020-12-30 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_models', '0004_auto_20201230_0024'),
        ('rental_objects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalobject',
            name='price_models',
        ),
        migrations.AddField(
            model_name='rentalobject',
            name='price_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price_models.pricemodel'),
        ),
    ]
