# Generated by Django 3.1.4 on 2020-12-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_objects', '0002_auto_20201229_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalobject',
            name='year_of_manufacture',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
